version: '2'
services:
  db:
    image: postgres
    ports:
      - '5432'
    volumes:
      - postgres-data:/data
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/redis
  web:
    build: .
    environment:
      EDITOR: vim
      RAILS_ENV: development
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/naughie
      - bundle-data:/usr/local/bundle
    links:
      - db
      - redis
volumes:
  bundle-data:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local
