sources:
  gcc: gcc
  gpp: g++
  latexmk: latexmk
  editor_buttons:
    md:
      h1:
        key: H1
        val: '# '
      h2:
        key: H2
        val: '## '
      h3:
        key: H3
        val: '### '
      h4:
        key: H4
        val: '#### '
      h5:
        key: H5
        val: '##### '
      h6:
        key: H6
        val: '###### '
      code:
        key: CODE
        val: '`'
      theorem:
        key: Thm
        val: "<span class='thm theorem'>\n\n</span>\n"
      lemma:
        key: Lem
        val: "<span class='thm lemma'>\n\n</span>\n"
      proposition:
        key: Prop
        val: "<span class='thm proposition'>\n\n</span>\n"
      corollary:
        key: Cor
        val: "<span class='thm corollary'>\n\n</span>\n"
      definition:
        key: Def
        val: "<span class='thm definition'>\n\n</span>\n"
      remark:
        key: Rem
        val: "<span class='thm remark'>\n\n</span>\n"
      proof:
        key: Proof
        val: "<span class='proof'>\n\n</span>\n"
      backslash:
        key: \
        val: \
      mathdollars:
        key: $...$
        val: $$
      mathdisplay:
        key: '\[...\]'
        val: "\\[\n\\]\n"
      align:
        key: align
        val: "\\begin{align}\n\\end{align}\n"
      alignstar:
        key: align*
        val: "\\begin{align*}\n\\end{align*}\n"
      ampersand:
        key: '&'
        val: '&'
      newline:
        key: \\
        val: ' \\'
      braces:
        key: '{...}'
        val: '{}'
      bracesdisp:
        key: '\{...\}'
        val: '\{\}'
      parantheses:
        key: '(...)'
        val: '()'
      brackets:
        key: '[...]'
        val: '[]'
      angles:
        key: '\langle...\rangle'
        val: '\langle\rangle'
      absolutevalue:
        key: '|...|'
        val: '||'
      norm:
        key: '\|...\|'
        val: '\|\|'
      leftbrace:
        key: '\left'
        val: '\left'
      rightbrace:
        key: '\right'
        val: '\right'
      middlebar:
        key: '\mid'
        val: '\mid'
      colon:
        key: '\colon'
        val: '\colon'
      pmatrix:
        key: pmatrix
        val: "\\begin{pmatrix}\n\\end{pmatrix}"
      cases:
        key: cases
        val: "\\begin{cases}\n\\end{cases}"
    html:
      h1:
        key: H1
        val: <h1></h1>
      h2:
        key: H2
        val: <h2></h2>
      h3:
        key: H3
        val: <h3></h3>
      h4:
        key: H4
        val: <h4></h4>
      h5:
        key: H5
        val: <h5></h5>
      h6:
        key: H6
        val: <h6></h6>
scopes:
  google_drive:
    - https://www.googleapis.com/auth/drive
